version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:5000
    networks:
      - default-network

networks:
  default-network:
    driver: bridge
